export const QUERY_KEYS = {
  JOB_DETAIL: "jobDetail",
  JOBS: "jobs",
  MY_JOBS: "myJobs",
  JOB_APPLICANTS: "jobApplicants",
  JOB_BOOKMARKS: "jobBookmarks",
  HOSPITAL_PROFILE: "hospitalProfile",
  VETERINARIAN_PROFILE: "veterinarianProfile",
  STUDENT_PROFILE: "studentProfile",
  RESUMES: "resumes",
  MY_RESUMES: "myResumes",
  RESUME_DETAIL: "resumeDetail",
  TRANSFERS: "transfers",
  TRANSFER_DETAIL: "transferDetail",
  FORUMS: "forums",
  FORUM_DETAIL: "forumDetail",
  LECTURES: "lectures",
  LECTURE_DETAIL: "lectureDetail",
} as const;