export * from './PrismaAuthRepository';
export * from './PrismaUserRepository';
export * from './PrismaJobRepository';
export * from './PrismaResumeRepository';
export * from './PrismaHospitalRepository';
export * from './PrismaTransferRepository';
export * from './PrismaLectureRepository';
export * from './PrismaApplicationRepository';
export * from './PrismaMessageRepository';